### ISSUE TITLE
"This Serverless Function has crashed." when opening docs.

### ISSUE THREAD

**Issue by schultek** [invertase/docs.page#267]
When I open my docs page, I get "This Serverless Function has crashed.":

https://docs.page/schultek/jaspr~develop

I don't really have anything else to go on or debug this myself. This was working a month ago or so.

**Comment by Ehesp** [comment]
Hmm not good - thought I handled these "gracefully". Will debug, here's the logs

```
[GET] /schultek/jaspr~develop
15:33:55:37
2023-01-26T15:33:56.167Z	988f8f06-c757-4947-809a-b397da4a2dbf	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read properties of undefined (reading 'startsWith')","reason":{"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'startsWith')","stack":["TypeError: Cannot read properties of undefined (reading 'startsWith')","    at isExternalLink (file:///var/task/dist/entry.js:2420:15)","    at Link (file:///var/task/dist/entry.js:2466:7)","    at Fb (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:65:44)","    at Ib (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)","    at W (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)","    at Eb (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:82:216)","    at Zb (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:99:157)","    at Object.exports.renderToStaticNodeStream (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:100:55)","    at file:///var/task/dist/entry.js:166:25","    at new Promise (<anonymous>)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read properties of undefined (reading 'startsWith')","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:539:35)","    at process.emit (node:domain:475:12)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
Runtime.Unknown
```

**Comment by Ehesp** [comment]
All sorted https://github.com/invertase/docs.page/commit/d3572491152531d32500d0d83c86e27373032eb7

**Comment by Ehesp** [comment]
Not sure what's going on here lol https://docs.page/schultek/jaspr~develop/core/ssr

**Comment by Ehesp** [comment]
That was a weird one. Also fixed.

**Comment by schultek** [comment]
Awesome, that was quick 👍🔥
